### PR TITLE
windows compatibility and more

### PR DESCRIPTION
**Pull request by Vandivier**
happy to separate these changes if needed, but maybe you will accept them all:

1. build-node npm script which builds on Windows

1. /js folder including dependencies for build-node

1. package.json changes allowing for `npm publish` executed [here](https://www.npmjs.com/package/asx-abm).

1. relative path changes in some js files required for rollup to execute

1. Readme changes indicating build-node for Windows, and the need to install node-gyp

1. git ignore changed to add default GitHub Node exclusions

1. git ignore changed to not ignore /scripts so gh-pages has access

1. wraplibplus description, removing commented code, and minor alignment eg value on same line

### CODE REVIEW

**Comment by backspaces** [comment]
With the greatest respect, I'm going to have to reject this PR.

Why? While *very* well done, the PR is too ambitious.

Details.

- Files changed: 27! Some are new but still, this is extreme.
- I assumed the changes would be limited to package.json and the node build scripts for windows compatibility.
- Relative paths: The conversion from:
    ../dist/three.wrapper.js
  to
    /dist/three.wrapper.js
  fails when dist is not in the server's root dir.
  Example: clone to ~/Downloads/test/asx and running
    http://localhost/home/Downloads/test/asx/models/?src/exit
  .. yields:
    Failed to load resource: the server responded with a status of 404 (Not Found) for: /dist/OrbitControls.wrapper.js etc
  .. thus breaking the build.
- Reformatting: I believe our editors differ a bit causing spurious changes
  to files. Several files have changes that apparently are editor differences.
  See: LICENSE, AS.js. May not be a big deal.
- Relative path depth: The generated file dist/AS.module.js went from:
    import THREE from '../dist/three.wrapper.js';
  to:
    import THREE from '../../../dist/three.wrapper.js';
  Why?
- build.js: I'd prefer avoiding a single command for the build. Why? It hides too many details from the developer. 
One simple example is `shell.cp('docs/README.md', '.')`. I decided to reverse the dependency .. the README.md in the repo is "boss" while docs/README.md is dependent. It's an ugly issue as most "derived" files in a repo are, but having the decision visible in the package.json avoids issues. This is pretty clearly stating the repo is boss for these:
    ```
    "docsfiles": [
      "dist",
      "models",
      "README.md"
    ],
    "build-docs": "cp -Rp `bin/pkgkey.js docsfiles` docs"
    ```
- js/: Why not just add to the bin/ dir? Actually we may want to rename bin/ to something that indicates the build .. like buildtools/ .. but because they're called from npm scripts, short is good. Something like npm/?
- rimraf: why not just keep in node_modules?
- graceful-fs: doesn't shx handle this?
- mkdirs-sync.js, win32.js: are they needed, not in shx?
- models/scripts: All models/scripts/*.js completely changed. Character codes? CRLF? System issues or like Reformatting above? It's a set of derived/constructed files for the "dual build" so something is making them differ even tho they appear identical. This would mean alternating windows/*nix builds would completely replace these! Serious .git bummer I think?
- Nit: having .gitignore include systems not used in the repo is misleading,
  it leads devs to believe they *are* used in the repo.
  This is better handled in the global .gitignore.
  Had me looking for grunt, yarn, bower etc! :) I'm a dummy.

OTOH, I made things harder, there was no need to mess with wraplibpluss. I should have removed it, it was there only if wraplib itself was not general enough.

**Comment by backspaces** [comment]
Whew! After all that:

Could we list the issues you've found and see if there is a simple solution? For example, I like the finding you made in wraplib, calling node directly rather than using the "shebang" #!/usr/bin/env node. Ditto creating a single build module exporting several utils needed in the universal windows/*nix build.

So the list would include:
- Use shx for commands not common between windows and *nix/mac.
- Avoid #!/usr/bin/env node, call w/ node
- Resolve backticks use on window
- Avoiding system & editor differences seen in models/scripts & Reformatting above. CRLF and character codes may be an issue?
- ...

OR: is there a more systemic solution like cygwin? There *has* to be a way for windows/mac/*nix to get along for npm builds.

I brought this up to my group: [SimTable](http://www.simtable.com/).  I asked how we are handling this in our several repos. Answer, alas, was to use a *nix system. The one core dev using windows just switched over to Mac for work related programming.

I think we could get the JS Nobel prize if we could advance the npm script build issues. My [Medium story](https://medium.com/@backspaces/es6-modules-part-1-migration-strategy-a48de0b7f112) points to using npm as a build tool:
- https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/
- https://medium.com/javascript-training/introduction-to-using-npm-as-a-build-tool-b41076f488b0
- https://corysimmons.com/writings/2016/node/introducing-package-script-manager
- https://www.sitepoint.com/guide-to-npm-as-a-build-tool/
- https://medium.freecodecamp.org/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8

.. maybe we can complete the technique?

**Comment by backspaces** [comment]
I have submitted an npm bug report: https://github.com/npm/npm/issues/18580

**Comment by Vandivier** [comment]
Lots of exciting directions this may go but as a general preface I'm highly motivated to get a working abm and only trivially motivated regarding the periphery, so I may not be entirely responsive until my current model is completed.

Npm as a build engine is great and I'd likely enjoy contributing later on.

It would be helpful for me if many of the questions were reshaped into tasks.

Various notes:

1. Are the various functions needed? Doesn't shx cut it? Yes, they are needed, no shx doesn't cut it in those cases. Eg shx won't take space separated multiple function inputs. (thus BUILD.forEachSpace)

1. Can we rename these folders and move the files around and split the build file into various commands to make it package.json-driven? Sure. Just specify the tasks.

1. What were the main issues I ran into? Mainly back-ticks and passing multiple space separated files into various commands.

**Comment by Vandivier** [comment]
ah but one thing you said sticks out..."breaking the build?" The build is certainly working for me so please double-confirm if you really can't get it to build:
`npm install`
`npm run build-node`

**Comment by Vandivier** [comment]
not sure if this is an issue or my own ignorance, but looking here in rollup.config.js I'm confused why we need globals at all:

      globals: { // id: name pairs (import name from id)
        '/Users/owen/Dropbox/src/asx/dist/stats.wrapper.js': 'Stats',
        '/Users/owen/Dropbox/src/asx/dist/dat.gui.wrapper.js': 'dat',
        '/Users/owen/Dropbox/src/asx/dist/three.wrapper.js': 'THREE',
        // Not currently needed, anonymous (no name) import used:
        // '/Users/owen/Dropbox/src/asx/dist/OrbitControls.wrapper.js': 'THREE.OrbitControls'
      },

I think during the build we can just var THREE = require('three.wrapper.js'); and so on because we are in dist and we already wrapped the libraries and moved 'em over

**Comment by backspaces** [comment]
I wasn't clear when I said "breaking the build".

The actual "npm run build-node" did not fail. The resulting code failed.

It failed to run the test models.  Did you try running all the models/ after you made the build? See my comment "Relative paths: The conversion from..." above.

My guess is that if you did, you ran the http server in the asx/ dir. That is a bad idea because it assumes the modeler places asx in their server's root dir. It may explain you're changing the code itself to import from /dist rather than ../dist.

**Comment by backspaces** [comment]
Re: globals in Rollup config. God yes that's ugly! I really would like a fix.

Here's the issue: Rollup wants to rollup the dependencies as well as the repo's modules. I don't know how to make Rollup simply know that the dependencies should not be included.

You mentioned `var THREE = require('three.wrapper.js');`. Is that put in the rollup config file? It sure would be nice to make the dependencies simpler to manage.

l googled a bit and found: 
  https://stackoverflow.com/questions/34049326/how-do-i-keep-bower-package-dependencies-out-of-my-rollup-bundle

Now I just gotta understand this!

**Comment by backspaces** [comment]
This has gotten broader than simply converting a npm-script based build to be cross-platform. Even the code has changed from relative paths to "repo breaking" absolute paths (I think). I.e. breaking the resulting code.

Here's what I really need to know: What *exactly* are the windows issues? 
Here's what I require: No code changes. And relatively minor changes to the existing build structure.

If backticks are the main issue, I think we can fix that by building our own backtick equivalent.

But the shell used by npm appears to be the core issue. I've submitted a github issue on that. It's absurd for a universal modules system to not be cross-platform. 

I don't know if we can specify the shell used by npm. If so, maybe we could get a windows version of bash and have windows users specify that.

The current (really sophisticated) node build makes me balk. It hides too many details like the copy issue that came up with README. And basically is equivalent to using build systems like gulp, grunt, browserify, webpack etc, etc which was the whole point of an npm build.

OTOH: would using a build system like gulp or webpack solve our problem? 

I'll remove the now-spurious wraplibplus.js shortly which should simplify the build a bit.

**Comment by Vandivier** [comment]
Closed as the changes will not be accepted

**Comment by backspaces** [comment]
Thank you.

Just FYI: I found an expert working at a moderate sized company and asked about this problem.
* Docker containers can be used to build a common dev environment which solve all cross platform issues. Pretty extreme!
* Using cygwin includes bash. Apparently it *should* be possible to change the default npm shell to bash. But some have run [into problems](https://stackoverflow.com/questions/23243353/how-to-set-shell-for-npm-run-scripts-in-windows) so simply use `bash rm -rf tempdir`
* Moving away from npm for builds to gulp or similar *may* work due to being all JS based. Some have reported that this is not the case.

**Pull request closed without merging**
