### PR TITLE
offscreen canvas, needed for web worker

### PR DESCRIPTION
**Pull request by m0ose**
- The option to use offscreen canvas.
  - this is needed for web workers to use models, since they dont have a dom.

### CODE REVIEW

**Comment by backspaces** [comment]
I'm concerned just how much this touches in AS. I'm reminded how complicated things got in AS1 when like Mouse went from tiny to way too complicated. Then everything got "evented". And then "headless" took over. What a mess! We may be able to simplify at a different level.

From what I can tell, there are lots of strategies for workers. Mainly which part of the code is most likely to be in the worker, and which in the main thread.

I.e. you could have "step" as a worker, maybe, thus not needing drawing help. The opposite approach is have "draw" as a worker, needing canvas help.

So my concern is: what if we do a lot of "if worker do foo, otherwise bar" and it eventually does not fit the final worker strategy?

Let talk next week. You can step me through this.

BTW: Is ctx.offscreenCanvas this: 
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas
My near-zero knowledge of workers is a problem!

**Comment by m0ose** [comment]
Should I close this pull request, as not being immediatly useful, understood, or supported?

**Comment by backspaces** [comment]
No need to close it, is there? It at least lets us know we want to be able
to use workers but need to discuss how.

**Comment by backspaces** [comment]
@m0ose Hi. I think as-core handles this now. @stigmergic has core running in a worker and we'll add that to as-core shortly.

**Pull request closed without merging**
