### PR TITLE
Navier Stokes fluids

### PR DESCRIPTION
**Pull request by m0ose**
This is just for examining. I have 2 major questions. 
* Why is it going so slow ? 
* Does it look accurate to the paper?
* Short of going full webgl how can it be speed up ?

### CODE REVIEW

**Comment by backspaces** [comment]
Don't know what the issue is, probably a deep probe needed. Sigh :)

Observations:
- I like the idea of adding lib/ & test/lib to .gitignore. Maybe docs/ too.
  "Derived" files are a pain trying to figure out PRs and commit changes.
  Just cloning and running npm run all is much better, thanks.
- Re: [this.width, this.height, this.data] = [width, height, data].
  I'd hate to toss a nice es6 feature if it's soon to be optimized.
  Is this a problem in Canary too?  Maybe some quick console.time / util.timeit tests?
- I like the 'inBounds' method, much clearer. Could be simplified to:
  inBounds (x, y) { return u.between(x, 0, this.width - 1) && u.between(y, 0, this.height - 1) right?
- LOVE the idea of using the test/apps for trying new stuff. Maybe a new module soon?
- Is `const` also a performance problem? I.e.:
```
 -    const f10 = this.data[i + 1] || 0 // 0 at bottom right corner
 -    const f01 = this.data[i + w] || 0 // 0 at all bottom row
 -    const f11 = this.data[i + 1 + w] || 0 // 0 at end of next to bottom row
 +    var f10 = this.data[i + 1] || 0 // 0 at bottom right corner
 +    var f01 = this.data[i + w] || 0 // 0 at all bottom row
 +    var f11 = this.data[i + 1 + w] || 0 // 0 at end of next to bottom row
```
- More later but main concern is abandoning es6 if we can avoid it. If it is horiffic now, maybe make these inline changes and put a NOTE: or REMIND: comment to fix when performance is OK. Really surprised var is better than const. Maybe let? But probably relates to the difficulty of local scope.

**Comment by backspaces** [comment]
Oh, remind me: What's the git fu needed to get your PR cloned to my computer w/o committing first? Then I can do some timing too just to make sure we get the same results. Pushing me to be more PR savvy is a Good Thing!

**Comment by backspaces** [comment]
Closing for more recent Nav2.

**Comment by m0ose** [comment]
This has been deprecated.

**Pull request closed without merging**
