### PR TITLE
Prototype of firebase plugin

### PR DESCRIPTION
**Pull request by m0ose**
This is a sketch for Owen to look at. Not intended to be merged. 

This plugin can post turtle locations to FB:

How to run with Chrome Canary:
* navigate Canary to : http://127.0.0.1/Documents/asx/models/index.html?src/flockFB
* navigate another browser to : http://dev.simtable.com/Clipboard/index.html?id=%22st_rivertonPokemon_2568%22#MapWindow

Bugs:
* When I changed the bounds of the world to those of California, they stopped showing up in ASX.
* clipboard is not erasing old geojsons

### CODE REVIEW

**Comment by backspaces** [comment]
I like the idea of independent libraries that can be used with the CoreAS. We've had a few discussions on how to do this including an "umbrella" name with the core repo there, and independent repos too .. see how these guys manage it: https://github.com/stackgl

Let's chat about how eventing and animators fit together. I haven't had time lately to look into this but it seems like a good idea.

**Comment by backspaces** [comment]
Back from a family issue .. sorry for being incomplete.  I think the high
order bit here is to get stephen to define a bit more clearly the
architecture for all the changes we've been going through.

The CoreAS repo is getting pretty nearly complete, I'll be happy with it
after converting all/most of the asx models to run with core. I think this
is just tossing all view related stuff, but we'll see.

But once that's done, we can ponder all the convenience stuff like the
animator and other add-ons.

Give it some thought and see what you think.

**Comment by backspaces** [comment]
Finally got around to looking at the code after the huge job of converting to CoreAS. Nice! Love crush. : ) Maybe the AS mascot?!

Thoughts:
* Should we do evented (& animator?) with CoreAS? 
  * I was against it initially but now that I'm finally done, and evented is nicely done and integrated into animator, it may solve stephen's problems with multiple scenarios.
* Maybe the animator should simply listen to events too? ..i.e. make the animator evented and make evented a core capability.
* Is evented general enough to be used in all the simtable scenarios? If so it definitely should be considered for CoreAS

**Comment by m0ose** [comment]
Crush: Oh are you awake dude!
Marlin: What are you talking about?
Crush: Saw the whole thing dude! First you were like woah! [twirling] and then you were like WOAH! [clapping his hands on his head] and the you were like woah! {sighing] You got some serious thrill issues dude, taking out all the jellies.

**Comment by backspaces** [comment]
@m0ose @stigmergic: closing this for now, it's on the table so to speak. We talked about multiple animators yesterday (homework wed) and having the animators outside of the Model and a couple of separate modules. So I'll close this for now. 

BTW: we'll likely use Evented two ways: one to step models, one to emit events to listeners.

**Pull request closed without merging**
